#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bugeceson
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Portfoy")]
	public partial class PortfoyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PortfoyDataContext() : 
				base(global::bugeceson.Properties.Settings.Default.PortfoyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PortfoyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortfoyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortfoyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortfoyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<YONETICI> YONETICIs
		{
			get
			{
				return this.GetTable<YONETICI>();
			}
		}
		
		public System.Data.Linq.Table<BIREYSEL_KULLANICI> BIREYSEL_KULLANICIs
		{
			get
			{
				return this.GetTable<BIREYSEL_KULLANICI>();
			}
		}
		
		public System.Data.Linq.Table<KURUMSAL_KULLANICI> KURUMSAL_KULLANICIs
		{
			get
			{
				return this.GetTable<KURUMSAL_KULLANICI>();
			}
		}
		
		public System.Data.Linq.Table<KURUMSAL_PORTFOY> KURUMSAL_PORTFOYs
		{
			get
			{
				return this.GetTable<KURUMSAL_PORTFOY>();
			}
		}
		
		public System.Data.Linq.Table<BIREYSEL_PORTFOY> BIREYSEL_PORTFOYs
		{
			get
			{
				return this.GetTable<BIREYSEL_PORTFOY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YONETICI")]
	public partial class YONETICI
	{
		
		private string _kullanici_adi;
		
		private string _sifre;
		
		public YONETICI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this._kullanici_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this._sifre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BIREYSEL_KULLANICI")]
	public partial class BIREYSEL_KULLANICI
	{
		
		private string _kullanici_adi;
		
		private string _ad;
		
		private string _soyad;
		
		private string _email;
		
		private string _dogum_tarihi;
		
		private string _sifre;
		
		public BIREYSEL_KULLANICI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this._kullanici_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this._ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string soyad
		{
			get
			{
				return this._soyad;
			}
			set
			{
				if ((this._soyad != value))
				{
					this._soyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogum_tarihi", DbType="NVarChar(50)")]
		public string dogum_tarihi
		{
			get
			{
				return this._dogum_tarihi;
			}
			set
			{
				if ((this._dogum_tarihi != value))
				{
					this._dogum_tarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this._sifre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KURUMSAL_KULLANICI")]
	public partial class KURUMSAL_KULLANICI
	{
		
		private string _kullanici_adi;
		
		private string _email;
		
		private string _sirket_adi;
		
		private string _sirket_adresi;
		
		private string _kurulus_tarihi;
		
		private string _sifre;
		
		public KURUMSAL_KULLANICI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this._kullanici_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this._sirket_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adresi", DbType="NVarChar(MAX)")]
		public string sirket_adresi
		{
			get
			{
				return this._sirket_adresi;
			}
			set
			{
				if ((this._sirket_adresi != value))
				{
					this._sirket_adresi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurulus_tarihi", DbType="NVarChar(50)")]
		public string kurulus_tarihi
		{
			get
			{
				return this._kurulus_tarihi;
			}
			set
			{
				if ((this._kurulus_tarihi != value))
				{
					this._kurulus_tarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this._sifre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KURUMSAL_PORTFOY")]
	public partial class KURUMSAL_PORTFOY
	{
		
		private string _kullanici_adi;
		
		private string _sirket_adi;
		
		private string _yetkili;
		
		private string _telefon;
		
		private string _hisse;
		
		private string _artis_azalis;
		
		private string _hisse_payi;
		
		private string _tahvil;
		
		private string _anapara;
		
		private string _basit_faiz;
		
		private string _bilesik_faiz;
		
		private string _nakit_para;
		
		public KURUMSAL_PORTFOY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this._kullanici_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this._sirket_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetkili", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string yetkili
		{
			get
			{
				return this._yetkili;
			}
			set
			{
				if ((this._yetkili != value))
				{
					this._yetkili = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NVarChar(50)")]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this._telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hisse", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hisse
		{
			get
			{
				return this._hisse;
			}
			set
			{
				if ((this._hisse != value))
				{
					this._hisse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artis_azalis", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string artis_azalis
		{
			get
			{
				return this._artis_azalis;
			}
			set
			{
				if ((this._artis_azalis != value))
				{
					this._artis_azalis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hisse_payi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hisse_payi
		{
			get
			{
				return this._hisse_payi;
			}
			set
			{
				if ((this._hisse_payi != value))
				{
					this._hisse_payi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tahvil", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tahvil
		{
			get
			{
				return this._tahvil;
			}
			set
			{
				if ((this._tahvil != value))
				{
					this._tahvil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anapara", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string anapara
		{
			get
			{
				return this._anapara;
			}
			set
			{
				if ((this._anapara != value))
				{
					this._anapara = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basit_faiz", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basit_faiz
		{
			get
			{
				return this._basit_faiz;
			}
			set
			{
				if ((this._basit_faiz != value))
				{
					this._basit_faiz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bilesik_faiz", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string bilesik_faiz
		{
			get
			{
				return this._bilesik_faiz;
			}
			set
			{
				if ((this._bilesik_faiz != value))
				{
					this._bilesik_faiz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nakit_para", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nakit_para
		{
			get
			{
				return this._nakit_para;
			}
			set
			{
				if ((this._nakit_para != value))
				{
					this._nakit_para = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BIREYSEL_PORTFOY")]
	public partial class BIREYSEL_PORTFOY
	{
		
		private string _kullanici_adi;
		
		private string _ad_soyad;
		
		private string _telefon;
		
		private string _hisse;
		
		private string _artis_azalis;
		
		private string _hisse_payi;
		
		private string _tahvil;
		
		private string _anapara;
		
		private string _basit_faiz;
		
		private string _bilesik_faiz;
		
		private string _nakit_para;
		
		public BIREYSEL_PORTFOY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kullanici_adi
		{
			get
			{
				return this._kullanici_adi;
			}
			set
			{
				if ((this._kullanici_adi != value))
				{
					this._kullanici_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad_soyad
		{
			get
			{
				return this._ad_soyad;
			}
			set
			{
				if ((this._ad_soyad != value))
				{
					this._ad_soyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NVarChar(50)")]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this._telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hisse", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hisse
		{
			get
			{
				return this._hisse;
			}
			set
			{
				if ((this._hisse != value))
				{
					this._hisse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artis_azalis", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string artis_azalis
		{
			get
			{
				return this._artis_azalis;
			}
			set
			{
				if ((this._artis_azalis != value))
				{
					this._artis_azalis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hisse_payi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hisse_payi
		{
			get
			{
				return this._hisse_payi;
			}
			set
			{
				if ((this._hisse_payi != value))
				{
					this._hisse_payi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tahvil", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tahvil
		{
			get
			{
				return this._tahvil;
			}
			set
			{
				if ((this._tahvil != value))
				{
					this._tahvil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anapara", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string anapara
		{
			get
			{
				return this._anapara;
			}
			set
			{
				if ((this._anapara != value))
				{
					this._anapara = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basit_faiz", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basit_faiz
		{
			get
			{
				return this._basit_faiz;
			}
			set
			{
				if ((this._basit_faiz != value))
				{
					this._basit_faiz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bilesik_faiz", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string bilesik_faiz
		{
			get
			{
				return this._bilesik_faiz;
			}
			set
			{
				if ((this._bilesik_faiz != value))
				{
					this._bilesik_faiz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nakit_para", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nakit_para
		{
			get
			{
				return this._nakit_para;
			}
			set
			{
				if ((this._nakit_para != value))
				{
					this._nakit_para = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
